// Generated by tools/build-art.ts from art/sheets.ts. Do not edit by hand.
// Colour numbers: 1..255 are masterColours indexes + 1; 0 is transparent.

export type Drawing = {
  sheet: string;
  x: number;
  y: number;
  width: number;
  height: number;
  pixels: Uint8Array;
};

function decode(base64: string): Uint8Array {
  const binary = atob(base64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

export const drawings: Record<string, Drawing> = {
  "!": { sheet: "font.png", x: 148, y: 0, width: 3, height: 5, pixels: decode("AEYAAEYAAEYAAAAAAEYA") },
  ".": { sheet: "font.png", x: 144, y: 0, width: 3, height: 5, pixels: decode("AAAAAAAAAAAAAAAAAEYA") },
  "0": { sheet: "font.png", x: 0, y: 0, width: 3, height: 5, pixels: decode("RkZGRgBGRgBGRgBGRkZG") },
  "1": { sheet: "font.png", x: 4, y: 0, width: 3, height: 5, pixels: decode("AEYARkYAAEYAAEYARkZG") },
  "2": { sheet: "font.png", x: 8, y: 0, width: 3, height: 5, pixels: decode("RkZGAABGRkZGRgAARkZG") },
  "3": { sheet: "font.png", x: 12, y: 0, width: 3, height: 5, pixels: decode("RkZGAABGRkZGAABGRkZG") },
  "4": { sheet: "font.png", x: 16, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGRkZGAABGAABG") },
  "5": { sheet: "font.png", x: 20, y: 0, width: 3, height: 5, pixels: decode("RkZGRgAARkZGAABGRkZG") },
  "6": { sheet: "font.png", x: 24, y: 0, width: 3, height: 5, pixels: decode("RkZGRgAARkZGRgBGRkZG") },
  "7": { sheet: "font.png", x: 28, y: 0, width: 3, height: 5, pixels: decode("RkZGAABGAABGAABGAABG") },
  "8": { sheet: "font.png", x: 32, y: 0, width: 3, height: 5, pixels: decode("RkZGRgBGRkZGRgBGRkZG") },
  "9": { sheet: "font.png", x: 36, y: 0, width: 3, height: 5, pixels: decode("RkZGRgBGRkZGAABGRkZG") },
  ":": { sheet: "font.png", x: 152, y: 0, width: 3, height: 5, pixels: decode("AAAAAEYAAAAAAEYAAAAA") },
  "A": { sheet: "font.png", x: 40, y: 0, width: 3, height: 5, pixels: decode("RkZGRgBGRkZGRgBGRgBG") },
  "B": { sheet: "font.png", x: 44, y: 0, width: 3, height: 5, pixels: decode("RkYARgBGRkYARgBGRkYA") },
  "C": { sheet: "font.png", x: 48, y: 0, width: 3, height: 5, pixels: decode("RkZGRgAARgAARgAARkZG") },
  "D": { sheet: "font.png", x: 52, y: 0, width: 3, height: 5, pixels: decode("RkYARgBGRgBGRgBGRkYA") },
  "E": { sheet: "font.png", x: 56, y: 0, width: 3, height: 5, pixels: decode("RkZGRgAARkZGRgAARkZG") },
  "F": { sheet: "font.png", x: 60, y: 0, width: 3, height: 5, pixels: decode("RkZGRgAARkZGRgAARgAA") },
  "G": { sheet: "font.png", x: 64, y: 0, width: 3, height: 5, pixels: decode("RkZGRgAARgBGRgBGRkZG") },
  "H": { sheet: "font.png", x: 68, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGRkZGRgBGRgBG") },
  "I": { sheet: "font.png", x: 72, y: 0, width: 3, height: 5, pixels: decode("RkZGAEYAAEYAAEYARkZG") },
  "J": { sheet: "font.png", x: 76, y: 0, width: 3, height: 5, pixels: decode("AABGAABGAABGRgBGAEYA") },
  "K": { sheet: "font.png", x: 80, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGRkYARgBGRgBG") },
  "L": { sheet: "font.png", x: 84, y: 0, width: 3, height: 5, pixels: decode("RgAARgAARgAARgAARkZG") },
  "M": { sheet: "font.png", x: 88, y: 0, width: 3, height: 5, pixels: decode("RgBGRkZGRkZGRgBGRgBG") },
  "N": { sheet: "font.png", x: 92, y: 0, width: 3, height: 5, pixels: decode("RkYARgBGRgBGRgBGRgBG") },
  "O": { sheet: "font.png", x: 96, y: 0, width: 3, height: 5, pixels: decode("RkZGRgBGRgBGRgBGRkZG") },
  "P": { sheet: "font.png", x: 100, y: 0, width: 3, height: 5, pixels: decode("RkZGRgBGRkZGRgAARgAA") },
  "Q": { sheet: "font.png", x: 104, y: 0, width: 3, height: 5, pixels: decode("RkZGRgBGRgBGRkZGAABG") },
  "R": { sheet: "font.png", x: 108, y: 0, width: 3, height: 5, pixels: decode("RkYARgBGRkYARgBGRgBG") },
  "S": { sheet: "font.png", x: 112, y: 0, width: 3, height: 5, pixels: decode("RkZGRgAARkZGAABGRkZG") },
  "T": { sheet: "font.png", x: 116, y: 0, width: 3, height: 5, pixels: decode("RkZGAEYAAEYAAEYAAEYA") },
  "U": { sheet: "font.png", x: 120, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGRgBGRgBGRkZG") },
  "V": { sheet: "font.png", x: 124, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGRgBGRgBGAEYA") },
  "W": { sheet: "font.png", x: 128, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGRkZGRkZGRgBG") },
  "X": { sheet: "font.png", x: 132, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGAEYARgBGRgBG") },
  "Y": { sheet: "font.png", x: 136, y: 0, width: 3, height: 5, pixels: decode("RgBGRgBGAEYAAEYAAEYA") },
  "Z": { sheet: "font.png", x: 140, y: 0, width: 3, height: 5, pixels: decode("RkZGAABGAEYARgAARkZG") },
};
