// XMAS-26 "Art build step and the rough Font sheet": the art build. A sheet
// is a drawn PNG plus the manifest of drawings cut from it; packing turns
// every pixel into a colour number (palette index + 1, 0 = transparent) so
// the site ships code, never PNGs.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { decodePng } from './png.ts';

export type DrawingSpec = { name: string; x: number; y: number; width: number; height: number };
export type SheetSpec = { file: string; width: number; height: number; drawings: DrawingSpec[] };
export type PackedDrawing = { width: number; height: number; pixels: Uint8Array };
export type ArtDrawing = PackedDrawing & { sheet: string; x: number; y: number };
export type ArtModule = Record<string, ArtDrawing>;

/** Any problem that must stop the build, with the file (and position) named. */
export class ArtBuildError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ArtBuildError';
  }
}

function hexAt(rgba: Uint8Array, at: number): string {
  return `#${[rgba[at], rgba[at + 1], rgba[at + 2]].map((b) => b.toString(16).padStart(2, '0')).join('')}`;
}

/**
 * Cuts every drawing out of the sheet, one colour number per pixel: 0 for
 * transparent, otherwise the palette index + 1. Throws ArtBuildError naming
 * the file and sheet position for a colour the master list does not allow.
 */
export function packSheet(spec: SheetSpec, png: Uint8Array, palette: readonly string[]): Record<string, PackedDrawing> {
  const image = decodePng(png);
  const first = spec.drawings.length > 0 ? ` (first drawing ${spec.drawings[0].name})` : '';
  if (image.width !== spec.width || image.height !== spec.height) {
    throw new ArtBuildError(
      `${spec.file}: expected a ${spec.width}x${spec.height} sheet, got ${image.width}x${image.height}${first}`,
    );
  }

  const numbers = new Map<string, number>();
  palette.forEach((hex, index) => numbers.set(hex.toLowerCase(), index + 1));

  const packed: Record<string, PackedDrawing> = {};
  for (const drawing of spec.drawings) {
    if (
      drawing.x < 0 ||
      drawing.y < 0 ||
      drawing.x + drawing.width > image.width ||
      drawing.y + drawing.height > image.height
    ) {
      throw new ArtBuildError(
        `${spec.file}: drawing ${drawing.name} at ${drawing.x},${drawing.y} (${drawing.width}x${drawing.height}) does not fit the ${image.width}x${image.height} sheet`,
      );
    }
    const pixels = new Uint8Array(drawing.width * drawing.height);
    for (let y = 0; y < drawing.height; y++) {
      for (let x = 0; x < drawing.width; x++) {
        const sheetX = drawing.x + x;
        const sheetY = drawing.y + y;
        const at = (sheetY * image.width + sheetX) * 4;
        const alpha = image.rgba[at + 3];
        if (alpha === 0) continue; // transparent, whatever RGB sits underneath
        const hex = hexAt(image.rgba, at);
        const number = numbers.get(hex);
        if (alpha !== 255 || number === undefined) {
          throw new ArtBuildError(
            `${spec.file}: pixel at ${sheetX},${sheetY} is ${hex} with alpha ${alpha}, not a master-list colour`,
          );
        }
        pixels[y * drawing.width + x] = number;
      }
    }
    packed[drawing.name] = { width: drawing.width, height: drawing.height, pixels };
  }
  return packed;
}

/** The GIMP palette of the master colour list, line n = colour number n. */
export function gplFile(name: string, palette: readonly string[]): string {
  let text = `GIMP Palette\nName: ${name}\nColumns: 0\n#\n`;
  for (const hex of palette) {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    text += `${String(r).padStart(3)} ${String(g).padStart(3)} ${String(b).padStart(3)}\t${hex}\n`;
  }
  return text;
}

const GENERATED_HEADER = [
  '// Generated by tools/build-art.ts from art/sheets.ts. Do not edit by hand.',
  '// Colour numbers: 1..255 are masterColours indexes + 1; 0 is transparent.',
  '',
  'export type Drawing = {',
  '  sheet: string;',
  '  x: number;',
  '  y: number;',
  '  width: number;',
  '  height: number;',
  '  pixels: Uint8Array;',
  '};',
  '',
  'function decode(base64: string): Uint8Array {',
  '  const binary = atob(base64);',
  '  const out = new Uint8Array(binary.length);',
  '  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);',
  '  return out;',
  '}',
  '',
  '',
].join('\n');

/** Writes the packed drawings as a small browser-safe TypeScript module. */
export function generateArtModule(drawings: ArtModule): string {
  const entries = Object.keys(drawings)
    .sort()
    .map((name) => {
      const drawing = drawings[name];
      const base64 = Buffer.from(drawing.pixels).toString('base64');
      return (
        `  ${JSON.stringify(name)}: { sheet: ${JSON.stringify(drawing.sheet)}, x: ${drawing.x}, y: ${drawing.y}, ` +
        `width: ${drawing.width}, height: ${drawing.height}, pixels: decode(${JSON.stringify(base64)}) },`
      );
    });
  return `${GENERATED_HEADER}export const drawings: Record<string, Drawing> = {\n${entries.join('\n')}${entries.length === 0 ? '' : '\n'}};\n`;
}

export type BuildArtOptions = {
  sheets: readonly SheetSpec[];
  sheetsDir: string;
  palette: readonly string[];
  moduleFile: string;
  gplFile: string;
  gplName: string;
};

/**
 * Packs every sheet and writes both outputs. Every sheet is read and packed
 * before anything is written, so a build that stops leaves no output behind
 * and does not touch output from an earlier run.
 */
export function buildArt(options: BuildArtOptions): void {
  const owners = new Map<string, string>();
  for (const spec of options.sheets) {
    for (const drawing of spec.drawings) {
      const owner = owners.get(drawing.name);
      if (owner !== undefined) {
        throw new ArtBuildError(`duplicate drawing name ${drawing.name} in ${spec.file}, already used by ${owner}`);
      }
      owners.set(drawing.name, spec.file);
    }
  }

  const drawings: ArtModule = {};
  for (const spec of options.sheets) {
    let png: Uint8Array;
    try {
      png = new Uint8Array(readFileSync(join(options.sheetsDir, spec.file)));
    } catch {
      throw new ArtBuildError(`${spec.file}: could not read the sheet`);
    }
    let packed: Record<string, PackedDrawing>;
    try {
      packed = packSheet(spec, png, options.palette);
    } catch (error) {
      if (error instanceof ArtBuildError) throw error;
      throw new ArtBuildError(`${spec.file}: ${error instanceof Error ? error.message : String(error)}`);
    }
    for (const drawing of spec.drawings) {
      const art = packed[drawing.name];
      drawings[drawing.name] = {
        sheet: spec.file,
        x: drawing.x,
        y: drawing.y,
        width: art.width,
        height: art.height,
        pixels: art.pixels,
      };
    }
  }

  const moduleText = generateArtModule(drawings);
  const gplText = gplFile(options.gplName, options.palette);
  writeFileSync(options.moduleFile, moduleText);
  writeFileSync(options.gplFile, gplText);
}
